// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelPlanner.Persistence;

#nullable disable

namespace TravelPlanner.Persistence.Migrations
{
    [DbContext(typeof(TravelPlannerDbContext))]
    partial class TravelPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ActivityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<TimeSpan?>("ActivityTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Activities");

                    b.HasIndex("TripPlanId");

                    b.ToTable("Activities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Activities_DateRequired", "ActivityDate > CONVERT(date, '00010101', 112)");

                            t.HasCheckConstraint("CK_Activities_EstimatedCost", "EstimatedCost >= 0");
                        });
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ChecklistItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_ChecklistItems");

                    b.HasIndex("TripPlanId");

                    b.ToTable("ChecklistItems", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.DestinationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Destinations");

                    b.HasIndex("TripPlanId");

                    b.ToTable("Destinations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Destinations_DateRange", "DepartureDate >= ArrivalDate");

                            t.HasCheckConstraint("CK_Destinations_DatesRequired", "ArrivalDate > CONVERT(date, '00010101', 112) AND DepartureDate > CONVERT(date, '00010101', 112)");
                        });
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ExpenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Expenses");

                    b.HasIndex("TripPlanId");

                    b.ToTable("Expenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Expenses_Amount", "Amount >= 0");
                        });
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.NoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Notes");

                    b.HasIndex("TripPlanId");

                    b.ToTable("Notes", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ReminderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ReminderAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_Reminders");

                    b.HasIndex("TripPlanId");

                    b.ToTable("Reminders", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Roles_Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ShareTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("TripPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK_ShareTokens");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("UQ_ShareTokens_Token");

                    b.HasIndex("TripPlanId");

                    b.ToTable("ShareTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_ShareTokens_AccessLevel", "AccessLevel IN (N'VIEW', N'EDIT')");
                        });
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.TripPlanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PlannedBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_TripPlans");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("IX_TripPlans_OwnerUserId");

                    b.ToTable("TripPlans", null, t =>
                        {
                            t.HasCheckConstraint("CK_TripPlans_DateRange", "EndDate >= StartDate");

                            t.HasCheckConstraint("CK_TripPlans_DatesRequired", "StartDate > CONVERT(date, '00010101', 112) AND EndDate > CONVERT(date, '00010101', 112)");

                            t.HasCheckConstraint("CK_TripPlans_PlannedBudget", "PlannedBudget >= 0");
                        });
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PK_UserRoles");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ActivityEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.TripPlanEntity", "TripPlan")
                        .WithMany("Activities")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Activities_TripPlans");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ChecklistItemEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.TripPlanEntity", "TripPlan")
                        .WithMany("ChecklistItems")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChecklistItems_TripPlans");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.DestinationEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.TripPlanEntity", "TripPlan")
                        .WithMany("Destinations")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Destinations_TripPlans");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.TripPlanEntity", "TripPlan")
                        .WithMany("Expenses")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Expenses_TripPlans");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.NoteEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.TripPlanEntity", "TripPlan")
                        .WithMany("NotesList")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notes_TripPlans");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ReminderEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.TripPlanEntity", "TripPlan")
                        .WithMany("Reminders")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reminders_TripPlans");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.ShareTokenEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.TripPlanEntity", "TripPlan")
                        .WithMany("ShareTokens")
                        .HasForeignKey("TripPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ShareTokens_TripPlans");

                    b.Navigation("TripPlan");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.TripPlanEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.UserEntity", "Owner")
                        .WithMany("TripPlans")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TripPlans_Users");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("TravelPlanner.Persistence.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne("TravelPlanner.Persistence.Entities.UserEntity", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.RoleEntity", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.TripPlanEntity", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("ChecklistItems");

                    b.Navigation("Destinations");

                    b.Navigation("Expenses");

                    b.Navigation("NotesList");

                    b.Navigation("Reminders");

                    b.Navigation("ShareTokens");
                });

            modelBuilder.Entity("TravelPlanner.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("TripPlans");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
